/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wekiinputhelper.gui;

import java.util.logging.Logger;
import wekiinputhelper.WekiInputHelper;

/**
 *
 * @author rebecca
 */
public class SendAndMonitorPanel extends javax.swing.JPanel {

    private WekiInputHelper w;
    private static final Logger logger = Logger.getLogger(SendAndMonitorPanel.class.getName());

    /**
     *
     * Creates new form AddInputsPanel
     */
    public SendAndMonitorPanel() {
        initComponents();
    }
    
    public void setWekiInputHelper(WekiInputHelper w) {
        this.w = w;
        updateFormForWeki();
    }

    private void updateFormForWeki() {
        //Set up input panels
        //Set up output panels
        //Add listeners: OSC in, send out, outputManager change    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSendWhen = new javax.swing.ButtonGroup();
        buttonGroupTriggerStop = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        inputParent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputScrollPane = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        nameValueRow1 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow2 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow3 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow4 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow5 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow6 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow7 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow8 = new wekiinputhelper.gui.NameValueRow();
        jSeparator1 = new javax.swing.JSeparator();
        outputParent = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        nameValueRow9 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow10 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow11 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow12 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow13 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow14 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow15 = new wekiinputhelper.gui.NameValueRow();
        nameValueRow16 = new wekiinputhelper.gui.NameValueRow();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new java.awt.GridLayout());

        inputParent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("5 values");

        jButton1.setText("Stop listening");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("OSC In");

        jLabel7.setText("Message /abc/1234");

        jLabel8.setText("Listening on port 6448");

        inputScrollPane.setPreferredSize(new java.awt.Dimension(260, 205));

        jPanel2.setPreferredSize(new java.awt.Dimension(255, 200));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jPanel2.add(nameValueRow1);
        jPanel2.add(nameValueRow2);
        jPanel2.add(nameValueRow3);
        jPanel2.add(nameValueRow4);
        jPanel2.add(nameValueRow5);
        jPanel2.add(nameValueRow6);
        jPanel2.add(nameValueRow7);
        jPanel2.add(nameValueRow8);

        inputScrollPane.setViewportView(jPanel2);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 10));
        jSeparator1.setSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout inputParentLayout = new javax.swing.GroupLayout(inputParent);
        inputParent.setLayout(inputParentLayout);
        inputParentLayout.setHorizontalGroup(
            inputParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputParentLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inputParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(inputParentLayout.createSequentialGroup()
                        .addGroup(inputParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        inputParentLayout.setVerticalGroup(
            inputParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(inputParentLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(inputParent);

        outputParent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("OSC Out");

        jLabel4.setText("17 values");

        jLabel5.setText("Sending to localhost on port 6449");

        jLabel6.setText("Message /osc/outputs/lalalalala");

        jButton2.setText("Start sending");

        jPanel3.setPreferredSize(new java.awt.Dimension(255, 200));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jPanel3.add(nameValueRow9);
        jPanel3.add(nameValueRow10);
        jPanel3.add(nameValueRow11);
        jPanel3.add(nameValueRow12);
        jPanel3.add(nameValueRow13);
        jPanel3.add(nameValueRow14);
        jPanel3.add(nameValueRow15);
        jPanel3.add(nameValueRow16);

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout outputParentLayout = new javax.swing.GroupLayout(outputParent);
        outputParent.setLayout(outputParentLayout);
        outputParentLayout.setHorizontalGroup(
            outputParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputParentLayout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(outputParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addGroup(outputParentLayout.createSequentialGroup()
                        .addGroup(outputParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        outputParentLayout.setVerticalGroup(
            outputParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputParentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(outputParent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSendWhen;
    private javax.swing.ButtonGroup buttonGroupTriggerStop;
    private javax.swing.JPanel inputParent;
    private javax.swing.JScrollPane inputScrollPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private wekiinputhelper.gui.NameValueRow nameValueRow1;
    private wekiinputhelper.gui.NameValueRow nameValueRow10;
    private wekiinputhelper.gui.NameValueRow nameValueRow11;
    private wekiinputhelper.gui.NameValueRow nameValueRow12;
    private wekiinputhelper.gui.NameValueRow nameValueRow13;
    private wekiinputhelper.gui.NameValueRow nameValueRow14;
    private wekiinputhelper.gui.NameValueRow nameValueRow15;
    private wekiinputhelper.gui.NameValueRow nameValueRow16;
    private wekiinputhelper.gui.NameValueRow nameValueRow2;
    private wekiinputhelper.gui.NameValueRow nameValueRow3;
    private wekiinputhelper.gui.NameValueRow nameValueRow4;
    private wekiinputhelper.gui.NameValueRow nameValueRow5;
    private wekiinputhelper.gui.NameValueRow nameValueRow6;
    private wekiinputhelper.gui.NameValueRow nameValueRow7;
    private wekiinputhelper.gui.NameValueRow nameValueRow8;
    private wekiinputhelper.gui.NameValueRow nameValueRow9;
    private javax.swing.JPanel outputParent;
    // End of variables declaration//GEN-END:variables

}
